### PR TITLE
Fixed feed name and image change when changing profile name and image

### LINKED ISSUE #272: Profile and feed not matching
In the latest version (0.9.32) In the latest version I can have a different name/image for my profile and for my channel. Since we don’t allow to dissociate profile and channel for now, this is confusing.

### PR DESCRIPTION
**Pull request by agazso**
Fixes #272 .

Changes proposed in this pull request:
- When updating the name or the image from the `IdentitySettings`(which should ideally be called `ProfileSettings`) it also updates the localFeed (if any).

### CODE REVIEW

File: src/containers/IdentitySettingsContainer.ts [hunk 1]
```diff
@@ -19,11 +20,24 @@ export const mapStateToProps = (state: AppState, ownProps: { navigation: TypedNa
 
 const mapDispatchToProps = (dispatch: any): DispatchProps => {
     return {
-        onUpdateAuthor: (text: string) => {
+        onUpdateAuthor: (text: string, ownFeed?: LocalFeed) => {
             dispatch(Actions.updateAuthorName(text));
+            if (ownFeed != null) {
```
Comment (vujevits) [inline src/containers/IdentitySettingsContainer.ts]: This looks fragile, it should be triggered by one action

File: src/containers/IdentitySettingsContainer.ts [hunk 2]
```diff
@@ -19,11 +20,24 @@ export const mapStateToProps = (state: AppState, ownProps: { navigation: TypedNa
...
+                dispatch(Actions.updateOwnFeed({
+                    feedUrl: ownFeed.feedUrl,
+                    name: text,
+                }));
+            }
         },
-        onUpdatePicture: (image: ImageData) => {
+        onUpdatePicture: (image: ImageData, ownFeed?: LocalFeed) => {
             dispatch(Actions.updateAuthorImage(image));
+            if (ownFeed != null) {
```
Comment (vujevits) [inline src/containers/IdentitySettingsContainer.ts]: Same here

File: src/containers/IdentitySettingsContainer.ts (hunk 1 above)
Comment (agazso) [reply src/containers/IdentitySettingsContainer.ts]: Changed

File: src/containers/IdentitySettingsContainer.ts (hunk 2 above)
Comment (agazso) [reply src/containers/IdentitySettingsContainer.ts]: Changed
