### PR TITLE
281 onboarding

### LINKED ISSUE #205: The check icon at the end of onboarding looks off on iPhoneX
**Describe the bug**
The check icon at the end of onboarding looks off on iPhoneX

**To Reproduce**
1. Reset App state
2. Click on Next
3. See error

**Expected behavior**
The check icon at the end of onboarding looks normal on iPhoneX

**Screenshots**
screen shot 2019-03-04 at 19 03 59

### LINKED ISSUE #213: Changing the name in onboarding is not working on android
**Describe the bug**
On the onboarding screen if you change the name it won't be saved, only the original name you added.

**To Reproduce**
1. Reset the App
2. Click on next
3. Enter name 
4. Add a profile picture
5. Change the name
6. Press checkmark
7. Go to Profile, you will see the name entered in step 3, not the one in step 5

**Smartphone (please complete the following information):**
Only on android, iOS works fine.

### LINKED ISSUE #281: Onboarding
Subtasks
- New launch screen
- New logo
- Customize existing onboarding component or create a new one that has all the features that we need
- Intro page
- Profile page
- Explore page
- Add specific channel page
- Channel list page
- Share your channel page

### LINKED ISSUE #325: Name editor in onboarding is covered by the keyboard
**Describe the bug**
When editing the name during the onboarding, the text input is covered by the keyboard.

**To Reproduce**
1. Reset the app
2. Click on Next
3. Edit text

**Expected behavior**
When editing the name during the onboarding, the text input is not covered by the keyboard.

**Smartphone (please complete the following information):**
It happened on every Samsung phone I have seen (Samsung Duos, Samsung Galaxy S7, Samsung Galaxy S10). Maybe Samsung have customised keyboards that are higher than the normal android keyboard.

### PR DESCRIPTION
**Pull request by vujevits**
don't merge before branch 287-bugreport-redesign is merged to master, it is merged into this one

Fixes #281 
Fixes #205 
Fixes #213 
Fixes #325 

Changes proposed in this pull request:
- using storyboard for iOS splash screen (changed build target to iOS 9.0)
- removed react-native-onboarding-swiper
- redesigned onboarding with an intro page and a second page for profile settings
   - for finishing onboarding has to pick picture & set a name
   - long press title to skip picture and name setting

TODO
- [x] android splash screen
- [ ] new default image

Not implementing the following features in this PR
- explore during onboarding
- add channel 
- share channel

### CODE REVIEW

File: src/ui/misc/FragmentSafeAreaView.tsx [hunk 1]
```diff
@@ -3,10 +3,18 @@ import { SafeAreaView, ViewProps } from 'react-native';
...
 import { StatusBarView } from '../../components/StatusBarView';
 
-export const FragmentSafeAreaViewWithoutTabBar = (props: ViewProps & { children: any }) => (
+interface OwnProps {
+    children: React.ReactNode | React.ReactNode[];
+    topBackgroundColor?: string;
+    bottomBackgroundColor?: string;
+}
+
+type Props = ViewProps & OwnProps;
```
Comment (agazso) [inline src/ui/misc/FragmentSafeAreaView.tsx]: Why `ViewProps` is needed here?

File: src/ui/screens/onboarding/Page.tsx [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+    backgroundColor: string;
+    safeAreaTopBackgroundColor?: string;
+    children: ReactNode | ReactNode[];
+    leftButton?: ButtonProps;
+    rightButton?: ButtonProps;
+}
+
+export const Page = (props: Props) => {
+    return (
+        <FragmentSafeAreaViewForTabBar
```
Comment (agazso) [inline src/ui/screens/onboarding/Page.tsx]: As there is no tab bar during the onboarding, shouldn't we use the `FragmentSafeAreaViewWithoutTabBar`?

File: src/ui/screens/onboarding/WelcomeScreen.tsx [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+        this.props.onStartDownloadFeeds();
+    }
+
+    public render() {
+        return (
+            <Page
+                backgroundColor={Colors.BRAND_PURPLE}
+                leftButton={{
+                    label: 'MORE ABOUT FELFELE',
+                    onPress: () => Linking.openURL('https://felfele.com'),
```
Comment (agazso) [inline src/ui/screens/onboarding/WelcomeScreen.tsx]: The address should be a const instead of a plain string literal.

File: src/ui/screens/onboarding/Page.tsx [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+            <View style={styles.buttonRow}>
+                {props.leftButton != null &&
+                <PageButton
+                    {...props.leftButton}
+                    color={Colors.DARK_GRAY}
+                />
+                }
+                {props.rightButton != null &&
+                <PageButton
+                    {...props.rightButton}
```
Comment (agazso) [inline src/ui/screens/onboarding/Page.tsx]: The right button text should be aligned to right instead of left.

**Comment by agazso** [comment]
Also I found that the new onboarding has this issue on iPhone 5s:
https://github.com/felfele/felfele/issues/325

Screen Shot 2019-04-24 at 21 25 53

File: src/ui/screens/onboarding/Page.tsx (hunk 2 above)
Comment (vujevits) [reply src/ui/screens/onboarding/Page.tsx]: there is, it's just not the react-navigation tabbar

File: src/ui/misc/FragmentSafeAreaView.tsx (hunk 1 above)
Comment (vujevits) [reply src/ui/misc/FragmentSafeAreaView.tsx]: I did not check if it was used, it can be removed.

File: src/ui/screens/onboarding/Page.tsx (hunk 4 above)
Comment (vujevits) [reply src/ui/screens/onboarding/Page.tsx]: Yes, we talked about it with @david-gauquelin, it'll be changed. I was not certain about it because the previous page has centered buttons.

File: src/ui/screens/onboarding/Page.tsx (hunk 2 above)
Comment (agazso) [reply src/ui/screens/onboarding/Page.tsx]: I don't really understand then

I thought the distinction between the two FragmentSafeAreaView is because the react-navigation tabbar is positioned absolutely from the bottom of the page and it's transparent, so the bottom unsafe area would have to styled differently and a padding should be added.

Also if you use the `FragmentSafeAreaViewWithoutTabBar` here there is no visible difference.

**Comment by agazso** [comment]
The launch screen logo is oversized on iPhone 5s:

Screen Shot 2019-04-25 at 11 11 23

File: src/ui/screens/onboarding/Page.tsx (hunk 2 above)
Comment (vujevits) [reply src/ui/screens/onboarding/Page.tsx]: You also need it because of the different color for the top and bottom part of the safearea. The naming is probably still wrong.

**Comment by agazso** [comment]
The long press title to skip picture and name setting is missing. This would break Detox tests.

**Comment by vujevits** [comment]
opened #336 #337 #338 #339, I believe that covers everything missing, and this can be merged. @agazso can you have a look at it?

**Comment by agazso** [comment]
I tried it on android and it has the issue that the keyboard covers the name input (#325).

This paired with the new behavior that we don't let the user press the `Next` button until they changed their name make it very easy to get stuck in the onboarding. It took me 5 minutes to realize that I have to change the name in order to proceed, so I think now it is a critical issue.

Some ideas to mitigate this:
1. Don't make changing the name obligatory
2. Indicate somewhere you have to change your name (somewhere which is not covered by the keyboard). Or grey out the `Next` button, because it's not clear currently that it's disabled.
3. Fix the original issue and make the profile screen keyboard avoiding

Screen Shot 2019-04-29 at 22 15 12

**Comment by vujevits** [comment]
You have to love this remark in the KeyboardAvoidingView docs:
"Note: Android and iOS both interact with this prop differently. Android may behave better when given no behavior prop at all, whereas iOS is the opposite."
